// <auto-generated />
using LogisticsTrackingAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LogisticsTrackingAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260403234707_ExpansionPack")]
    partial class ExpansionPack
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LogisticsTrackingAPI.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CurrentDay")
                        .HasColumnType("integer");

                    b.Property<int>("FleetSize")
                        .HasColumnType("integer");

                    b.Property<bool>("HasAdvancedGPS")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasBankLoan")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasPremiumTires")
                        .HasColumnType("boolean");

                    b.Property<decimal>("LoanDebt")
                        .HasColumnType("numeric");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("NetWorth")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("LogisticsTrackingAPI.Models.Trip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ContractorNPC")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("IncidentLogs")
                        .HasColumnType("text");

                    b.Property<decimal>("KmCosts")
                        .HasColumnType("numeric");

                    b.Property<decimal>("NetProfit")
                        .HasColumnType("numeric");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Revenue")
                        .HasColumnType("numeric");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("TaxesAmount")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.ToTable("Trips");
                });

            modelBuilder.Entity("LogisticsTrackingAPI.Models.Trip", b =>
                {
                    b.HasOne("LogisticsTrackingAPI.Models.Player", "Player")
                        .WithMany("Trips")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("LogisticsTrackingAPI.Models.Player", b =>
                {
                    b.Navigation("Trips");
                });
#pragma warning restore 612, 618
        }
    }
}
